# Practice Pytorch

In [23]:
import torch

def activation(x):
    return 1 / (1 + torch.exp(-x))

torch.manual_seed(7)

# random normal variable of size 1,5
features = torch.randn((1,5))
print("features : ",features , features.shape)

# weights -> random normal variable with the shape of features
weights = torch.randn_like(features)
print("weights : ",weights, weights.shape)

bias = torch.randn(1, 1)
print("bias : ",bias, bias.shape)

features :  tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]]) torch.Size([1, 5])
weights :  tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]]) torch.Size([1, 5])
bias :  tensor([[0.3177]]) torch.Size([1, 1])


To flip weights we can use: 
    - reshape
    - resize  -> if asked a shape which has more or less elements, it will cut off
    - view * it is preferred!!

In [22]:
mm = torch.mm(features, weights.view(5, 1))
print("weights : ",mm, mm.shape)

mm1 = torch.mm(features, weights.reshape(5, 1))
print("weights : ",mm1, mm1.shape)

#_in place operation
mm2 = torch.mm(features, weights.resize_(5, 1))
print("weights : ",mm2, mm2.shape)

weights :  tensor([[-0.0242]]) torch.Size([1, 1])
weights :  tensor([[-0.0242]]) torch.Size([1, 1])
weights :  tensor([[-0.0242]]) torch.Size([1, 1])


In [25]:
output  = activation(mm + bias)
output 

tensor([[0.5729]])

### converting torch to numpy & vv -> .numpy(), .from_numpy

these are oinplace conversions, changing one will change another!!!

In [29]:
import numpy as np

npvar = np.array([1, 2, 3])
npvar

array([1, 2, 3])

In [31]:
btor = torch.from_numpy(npvar)
btor

tensor([1, 2, 3], dtype=torch.int32)

In [33]:
npvar2 = btor.numpy()
npvar2

array([1, 2, 3])

In [40]:
btor.mul_(2)

tensor([2, 4, 6], dtype=torch.int32)

In [44]:
npvar

array([2, 4, 6])

In [42]:
npvar2

array([2, 4, 6])